#!/usr/bin/env bash

# Check for and load bash_utils if not already loaded
if ! type -t cecho > /dev/null; then
    source bash_utils
fi

database_exists()
{
    local dbname="$1"
    local -i count
    local -a query=(
        "SELECT COUNT(*)"
        "FROM information_schema.SCHEMATA"
        "WHERE SCHEMA_NAME='${dbname}'"
        )
    count=$( mysql -BN -e "${query[*]}" )

    if [ "$?" -ne 0 ]; then
        cecho "database_exists query failed. Terminating program."
        exit 1
    fi

    [ "$count" -eq 1 ]
}

table_exists()
{
    local dbname="$1"
    local tablename="$2"
    local -i count
    local -a query=(
        "SELECT COUNT(*)"
        "FROM information_schema.TABLES"
        "WHERE TABLE_SCHEMA='${dbname}'"
        "AND TABLE_NAME='${tablename}'"
        )
    count=$( mysql -BN -e "${query[*]}" )
    
    if [ "$?" -ne 0 ]; then
        cecho "table_exists query failed. Terminating program."
        exit 1
    fi

    [ "$count" -eq 1 ]
}

proc_exists()
{
    local dbname="$1"
    local procname="$2"
    local -i count
    local -a query=(
        "SELECT COUNT(*)"
        "FROM information_schema.ROUTINES"
        "WHERE ROUTINE_SCHEMA='${dbname}'"
        "AND ROUTINE_NAME='${procname}'"
        )
    count=$( mysql -BN -e "${query[*]}" )
    
    if [ "$?" -ne 0 ]; then
        cecho "proc_exists query failed. Terminating program."
        exit 1
    fi

    [ "$count" -eq 1 ]
}

terminate_on_missing_proc()
{
    local dbase="$1"
    local procname="$2"

    if ! proc_exists "$dbase" "$procname"; then
        cecho "Procedure '${procname}' is missing. Terminating script." red
        exit 1
    fi
}



